---
- name: Install and start nginx
  hosts: all
  become: true
  tasks: null
- name: install nginx
  apt:
    name: nginx
    state: present
- name: Start nginx
  service:
    name: nginx
    state: started
